"""Core module for the Agentic Coding System.

This module exports the fundamental interfaces and exceptions used throughout
the system.
"""

from .exceptions import (
    AgenticSystemError,
    AgentCommunicationError,
    AgentError,
    AgentInitializationError,
    AgentOverloadError,
    APIError,
    APIKeyError,
    APIRateLimitError,
    APIResponseError,
    APITimeoutError,
    ArtifactDependencyError,
    ArtifactError,
    ArtifactNotFoundError,
    ArtifactVersionConflictError,
    CompilationError,
    ConfigurationError,
    InvalidConfigurationError,
    MissingConfigurationError,
    QualityCheckError,
    TaskDependencyError,
    TaskDecompositionError,
    TaskError,
    TaskExecutionError,
    TestFailureError,
    VerificationError,
)
from .interfaces import (
    Agent,
    AgentRole,
    Artifact,
    ArtifactManager,
    ArtifactType,
    LearningEngine,
    MetaAgentInterface,
    PromptTemplate,
    Task,
    TaskContext,
    TaskPriority,
    TaskStatus,
    Verifier,
)
from .task_result import TaskResult

__all__ = [
    # Interfaces
    "Agent",
    "AgentRole",
    "Artifact",
    "ArtifactManager",
    "ArtifactType",
    "LearningEngine",
    "MetaAgentInterface",
    "PromptTemplate",
    "Task",
    "TaskContext",
    "TaskPriority",
    "TaskResult",
    "TaskStatus",
    "Verifier",
    # Exceptions
    "AgenticSystemError",
    "AgentCommunicationError",
    "AgentError",
    "AgentInitializationError",
    "AgentOverloadError",
    "APIError",
    "APIKeyError",
    "APIRateLimitError",
    "APIResponseError",
    "APITimeoutError",
    "ArtifactDependencyError",
    "ArtifactError",
    "ArtifactNotFoundError",
    "ArtifactVersionConflictError",
    "CompilationError",
    "ConfigurationError",
    "InvalidConfigurationError",
    "MissingConfigurationError",
    "QualityCheckError",
    "TaskDependencyError",
    "TaskDecompositionError",
    "TaskError",
    "TaskExecutionError",
    "TestFailureError",
    "VerificationError",
]